[tool.commitizen]
version = "2.1.0"
bump_message = "chore(release): $current_version -> $new_version [skip-ci]"
version_files = [
    "src/YTMDesktopPlugin/Properties/AssemblyInfo.cs",
    "src/YTMDesktopPlugin/metadata/LoupedeckPackage.yaml"
]
tag_format = "v$version"